### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by rollingSirius** [arrti/myF2E#1]
最近在写一个小项目联系，在分页这一部分卡住了。请教一下大神：
我是按照这个进行实现的：
http://stackoverflow.com/questions/15981257/can-tornado-handle-pagination
html部分如下：
{% for news in news_timeline %}
<a href = "{{ news["news_link"] }}">{{ news["news_name"] }}</a>
{% end %}
{% module Paginator(current_page,5, len(news_timeline)) %}

下面会有分页的链接，但是这样之后不论怎么变换 Pagunator 的值都会将所有  news_name 列出来，并没有实现真正的分页。求教！

**Comment by arrti** [comment]
不好意思，最近没有上github，才看到，我可不是大神，是小白一枚。我对你的问题不是很明白，你说的没有实现真正的分页的意思是点击每一页的链接都会加载全部的内容?如果是这样的话，以F2E的实现为例，这部分需要在数据库查询的时候做，也就是说点击每一页的链接，如第2页，需要查询1次数据库，根据每页显示的内容（假如是10）以及当前页码（这里是2）来返回当前页的内容（也就是第11条记录到第20条记录），是这样的。你这里的 Paginator我没理解错的话应该是生产分页链接用的，并不是实现内容上的分页。不知对不对，多交流哈。
